# Site settings
title: RCDevlog
email: chan.wai.fu.ralph@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog I use to record down the problems I faced during development and how to solve them.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://redcomethk.github.io" # the base hostname & protocol for your site
twitter_username: redcomethk
github_username:  redcomethk

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal